class test_t {
    class lolo_t {
	int titi;
	//int majoliemethode() { return 42; }
    }
    
    int a;
    lolo_t lala;

    static float operator_plus(float a, lolo_t l) {
	return a + l.titi;
    }
    
    int toto(int x, float y)
    {
	lolo_t b;

	b.titi;
	this.lala.titi;
	//lala.titi + this.lala.majoliemethode();
	return (a + x / y + a) * x + b.titi + b;
    }
}



int main() {
    test_t test;

    return test.toto(10, 3.5);
}
