
class toto_t {
    var int a;
    //var test_t b;
    //var toto_t b;
}

class test_t {
    var int a;

    var toto_t b;

    func int __operator_plus(int x) {
	return a + x + b.a;
    }

    func test_t __operator_plus(test_t other) {
	var test_t res;
	res.a = a + other.a;
	return res;
    }
}

func void test(test_t t) {
    t.a = 30;
}

func int main() {

    var test_t *a;
    var test_t b, c;

    a = new test_t;

    a.a = 42;
    a.b.a = 10;

    test(b);

    c = b + a + b;

    return a + b.a + c.a;
}

