class test_t {
    class lolo_t {
	int titi;
	int majoliemethode() {
	    return 42;
	}
    }
    
    int a;
    lolo_t lala;

    test_t jolie() {
	return this;
    }

    static float __operator_plus(float a, lolo_t l) {
	return a + l.titi;
    }
    
    /*static*/ int with_closure() { // static is forbiden because the method access non static members
	toto(32, 5.3);
	return a;
    }

    int toto(int x, float y)
    {
	lolo_t b;
	b = new lolo_t;

	/*class pipo_t {
	    int bambi;
	    int with_closure() {
		return x;
	    }
	    };

	    pipo_t world;*/

	x + y;
	b.titi = b.titi = 32;
	this.lala.titi;
	jolie().a;
	lala.titi + this.lala.majoliemethode();
	return (a + x / y + a) * x + (b.titi = 4) + b;
    }
}



int main() {
    test_t test/* = new test_t()*/;

    int a, b;
    a = b = 42;
    test = new test_t;

    return test.toto(10, 3.5);
}
